<a href="https://colab.research.google.com/github/krisadas/finrl-multiple/blob/main/FinRLManystock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mount Google Drive

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive/')

In [5]:
# Install the unstable development version in Jupyter notebook:
!pip install git+https://github.com/AI4Finance-LLC/FinRL-Library.git

Collecting git+https://github.com/AI4Finance-LLC/FinRL-Library.git
  Cloning https://github.com/AI4Finance-LLC/FinRL-Library.git to /tmp/pip-req-build-2i74a60i
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-LLC/FinRL-Library.git /tmp/pip-req-build-2i74a60i
  Resolved https://github.com/AI4Finance-LLC/FinRL-Library.git to commit 083192a2abbdcaa195bd945b35853212cd8b00d8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-uax34g3u/elegantrl_0f1fae577f0b4e75bdf7b5ac7d9bc1b6
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-uax34g3u/elegantrl_0f1fae577f0b4e75bdf7b5ac7d9bc1b6
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit c2939fefe0e3ec55601ded49e39fdf9d7d781ea0
  Preparing metadata (setup.py) ... done
Requirement already satisfied: jqdatasdk<2,>=1 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (1.9.6)
Requirement already satisfied: alpaca-trade-api<4,>=3 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (3.2.0)
Requirement already satisfied: wrds<4,>=3 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (3.2.0)
Requirement already satisfied: scikit-learn<2,>=1 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (1.5.2)
Requirement already satisfied: exchange-calendars<5,>=4 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (4.6)
Requirement already satisfied: stockstats<0.6,>=0.5 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (0.5.4)
Requirement already satisfied: pyfolio<0.10,>=0.9 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (0.9.2)
Requirement already satisfied: ccxt<4,>=3 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (3.1.60)
Requirement already satisfied: ray[default,tune]<3,>=2 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (2.39.0)
Requirement already satisfied: pyportfolioopt<2,>=1 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (1.5.5)
Requirement already satisfied: yfinance<0.3,>=0.2 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (0.2.50)
Requirement already satisfied: stable-baselines3[extra]>=2.0.0a5 in /opt/conda/lib/python3.10/site-packages (from finrl==0.3.6) (2.5.0a0)
Requirement already satisfied: msgpack==1.0.3 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.0.3)
Requirement already satisfied: PyYAML==6.0.1 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (6.0.1)
Requirement already satisfied: urllib3<2,>1.24 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.26.14)
Requirement already satisfied: pandas>=0.18.1 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.2.3)
Requirement already satisfied: numpy>=1.11.1 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.26.4)
Requirement already satisfied: websockets<11,>=9.0 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (10.4)
Requirement already satisfied: aiohttp<4,>=3.8.3 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (3.11.8)
Requirement already satisfied: deprecation==2.1.0 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.1.0)
Requirement already satisfied: requests<3,>2 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.32.3)
Requirement already satisfied: websocket-client<2,>=0.56.0 in /opt/conda/lib/python3.10/site-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (0.58.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.6) (23.2)
Requirement already satisfied: certifi>=2018.1.18 in /opt/conda/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.6) (2022.12.7)
Requirement already satisfied: yarl>=1.7.2 in /opt/conda/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.6) (1.18.0)
Requirement already satisfied: setuptools>=60.9.0 in /opt/conda/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.6) (65.6.3)
Requirement already satisfied: cryptography>=2.6.1 in /opt/conda/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.6) (39.0.1)
Requirement already satisfied: aiodns>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from ccxt<4,>=3->finrl==0.3.6) (3.2.0)
Requirement already satisfied: toolz in /opt/conda/lib/python3.10/site-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (0.12.0)
Requirement already satisfied: korean_lunar_calendar in /opt/conda/lib/python3.10/site-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (0.3.1)
Requirement already satisfied: pyluach in /opt/conda/lib/python3.10/site-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (2.2.0)
Requirement already satisfied: tzdata in /opt/conda/lib/python3.10/site-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (2024.2)
Requirement already satisfied: SQLAlchemy>=1.2.8 in /opt/conda/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (2.0.36)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (1.16.0)
Requirement already satisfied: thriftpy2!=0.5.1,>=0.3.9 in /opt/conda/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (0.5.2)
Requirement already satisfied: pymysql>=0.7.6 in /opt/conda/lib/python3.10/site-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (1.1.1)
Requirement already satisfied: matplotlib>=1.4.0 in /opt/conda/lib/python3.10/site-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (3.7.0)
Requirement already satisfied: empyrical>=0.5.0 in /opt/conda/lib/python3.10/site-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (0.5.5)
Requirement already satisfied: scipy>=0.14.0 in /opt/conda/lib/python3.10/site-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (1.12.0)
Requirement already satisfied: pytz>=2014.10 in /opt/conda/lib/python3.10/site-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (2022.7)
Requirement already satisfied: ipython>=3.2.3 in /opt/conda/lib/python3.10/site-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (8.10.0)
Requirement already satisfied: seaborn>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (0.12.2)
Requirement already satisfied: cvxpy<2.0.0,>=1.1.19 in /opt/conda/lib/python3.10/site-packages (from pyportfolioopt<2,>=1->finrl==0.3.6) (1.6.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (5.29.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (3.16.1)
Requirement already satisfied: frozenlist in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.5.0)
Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (8.0.4)
Requirement already satisfied: jsonschema in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (4.17.3)
Requirement already satisfied: aiosignal in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.3.1)
Requirement already satisfied: smart-open in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (5.2.1)
Requirement already satisfied: memray in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.14.0)
Requirement already satisfied: py-spy>=0.2.0 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.4.0)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (20.28.0)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2.10.2)
Requirement already satisfied: colorful in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.5.6)
Requirement already satisfied: prometheus-client>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.14.1)
Requirement already satisfied: grpcio>=1.42.0 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.68.0)
Requirement already satisfied: aiohttp-cors in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.7.0)
Requirement already satisfied: opencensus in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.11.4)
Requirement already satisfied: tensorboardX>=1.9 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2.6.2.2)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2022.11.0)
Requirement already satisfied: pyarrow>=6.0.1 in /opt/conda/lib/python3.10/site-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (18.1.0)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn<2,>=1->finrl==0.3.6) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn<2,>=1->finrl==0.3.6) (3.5.0)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (1.0.0)
Requirement already satisfied: cloudpickle in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.0.0)
Requirement already satisfied: torch<3.0,>=2.3 in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.5.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (5.9.0)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (13.9.4)
Requirement already satisfied: ale-py>=0.9.0 in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (0.10.1)
Requirement already satisfied: tensorboard>=2.9.1 in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.18.0)
Requirement already satisfied: opencv-python in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.10.0.84)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.64.1)
Requirement already satisfied: pillow in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (9.4.0)
Requirement already satisfied: pygame in /opt/conda/lib/python3.10/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.6.1)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /opt/conda/lib/python3.10/site-packages (from wrds<4,>=3->finrl==0.3.6) (2.9.10)
Requirement already satisfied: lxml>=4.9.1 in /opt/conda/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.9.1)
Requirement already satisfied: multitasking>=0.0.7 in /opt/conda/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.3.6)
Requirement already satisfied: peewee>=3.16.2 in /opt/conda/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (3.17.3)
Requirement already satisfied: html5lib>=1.1 in /opt/conda/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (1.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/conda/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.11.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/conda/lib/python3.10/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (2.4.6)
Requirement already satisfied: th in /opt/conda/lib/python3.10/site-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl->finrl==0.3.6) (0.4.1)
Requirement already satisfied: pycares>=4.0.0 in /opt/conda/lib/python3.10/site-packages (from aiodns>=1.1.1->ccxt<4,>=3->finrl==0.3.6) (4.5.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (4.0.3)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (0.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (6.1.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (22.1.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (2.4.4)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from ale-py>=0.9.0->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance<0.3,>=0.2->finrl==0.3.6) (2.3.2.post1)
Requirement already satisfied: cffi>=1.12 in /opt/conda/lib/python3.10/site-packages (from cryptography>=2.6.1->ccxt<4,>=3->finrl==0.3.6) (1.15.1)
Requirement already satisfied: osqp>=0.6.2 in /opt/conda/lib/python3.10/site-packages (from cvxpy<2.0.0,>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.6) (0.6.7.post3)
Requirement already satisfied: scs>=3.2.4.post1 in /opt/conda/lib/python3.10/site-packages (from cvxpy<2.0.0,>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.6) (3.2.7)
Requirement already satisfied: clarabel>=0.5.0 in /opt/conda/lib/python3.10/site-packages (from cvxpy<2.0.0,>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.6) (0.9.0)
Requirement already satisfied: pandas-datareader>=0.2 in /opt/conda/lib/python3.10/site-packages (from empyrical>=0.5.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.10.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /opt/conda/lib/python3.10/site-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (0.0.4)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.10/site-packages (from html5lib>=1.1->yfinance<0.3,>=0.2->finrl==0.3.6) (0.5.1)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.7.5)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (4.8.0)
Requirement already satisfied: traitlets>=5 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (5.7.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (3.0.36)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.18.1)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (2.18.0)
Requirement already satisfied: stack-data in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.2.0)
Requirement already satisfied: backcall in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.2.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (5.1.1)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.1.6)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (1.0.5)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (4.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default,tune]<3,>=2->finrl==0.3.6) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/conda/lib/python3.10/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default,tune]<3,>=2->finrl==0.3.6) (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3,>2->alpaca-trade-api<4,>=3->finrl==0.3.6) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3,>2->alpaca-trade-api<4,>=3->finrl==0.3.6) (2.0.4)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.10/site-packages (from SQLAlchemy>=1.2.8->jqdatasdk<2,>=1->finrl==0.3.6) (2.0.1)
Requirement already satisfied: absl-py>=0.4 in /opt/conda/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.1.0)
Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (3.4.1)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.2.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (0.7.2)
Requirement already satisfied: ply<4.0,>=3.4 in /opt/conda/lib/python3.10/site-packages (from thriftpy2!=0.5.1,>=0.3.9->jqdatasdk<2,>=1->finrl==0.3.6) (3.11)
Requirement already satisfied: Cython>=3.0.10 in /opt/conda/lib/python3.10/site-packages (from thriftpy2!=0.5.1,>=0.3.9->jqdatasdk<2,>=1->finrl==0.3.6) (3.0.11)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /opt/conda/lib/python3.10/site-packages (from torch<3.0,>=2.3->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (10.3.5.147)

In [6]:
import os
import pathlib
import pkg_resources
import pip
installedPackages = {pkg.key for pkg in pkg_resources.working_set}
required = {'yfinance', 'pandas', 'matplotlib', 'stockstats','stable-baselines3','gymnasium','tensorflow'}
missing = required - installedPackages
if missing:
    !pip install yfinance
    !pip install pandas
    !pip install matplotlib
    !pip install stockstats
    !pip install gymnasium
    !pip install stable-baselines3[extra]
    !pip install tensorflow #==1.15.4

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib
matplotlib.use('Agg')
import datetime
import os
#from finrl.config import config

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.agents.stablebaselines3.models import DRLAgent,DRLEnsembleAgent
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline

import sys
sys.path.append("../FinRL-Library")

In [15]:
!pip install pyfolio

Requirement already satisfied: pyfolio in /opt/conda/lib/python3.10/site-packages (0.9.2)
Requirement already satisfied: numpy>=1.11.1 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (1.26.4)
Requirement already satisfied: scipy>=0.14.0 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (1.12.0)
Requirement already satisfied: empyrical>=0.5.0 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (0.5.5)
Requirement already satisfied: pandas>=0.18.1 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (2.2.3)
Requirement already satisfied: scikit-learn>=0.16.1 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (1.5.2)
Requirement already satisfied: pytz>=2014.10 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (2022.7)
Requirement already satisfied: seaborn>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (0.12.2)
Requirement already satisfied: ipython>=3.2.3 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (8.10.0)
Requirement already satisfied: matplotlib>=1.4.0 in /opt/conda/lib/python3.10/site-packages (from pyfolio) (3.7.0)
Requirement already satisfied: pandas-datareader>=0.2 in /opt/conda/lib/python3.10/site-packages (from empyrical>=0.5.0->pyfolio) (0.10.0)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (3.0.36)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (0.18.1)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (2.18.0)
Requirement already satisfied: stack-data in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (0.2.0)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (0.1.6)
Requirement already satisfied: backcall in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (0.2.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (5.1.1)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (4.8.0)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (0.7.5)
Requirement already satisfied: traitlets>=5 in /opt/conda/lib/python3.10/site-packages (from ipython>=3.2.3->pyfolio) (5.7.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (9.4.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=1.4.0->pyfolio) (1.0.5)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.18.1->pyfolio) (2024.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.16.1->pyfolio) (3.5.0)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.16.1->pyfolio) (1.4.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.10/site-packages (from jedi>=0.16->ipython>=3.2.3->pyfolio) (0.8.3)
Requirement already satisfied: lxml in /opt/conda/lib/python3.10/site-packages (from pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio) (4.9.1)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/lib/python3.10/site-packages (from pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio) (2.32.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.10/site-packages (from pexpect>4.3->ipython>=3.2.3->pyfolio) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.30->ipython>=3.2.3->pyfolio) (0.2.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=1.4.0->pyfolio) (1.16.0)
Requirement already satisfied: asttokens in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython>=3.2.3->pyfolio) (2.0.5)
Requirement already satisfied: executing in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython>=3.2.3->pyfolio) (0.8.3)
Requirement already satisfied: pure-eval in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython>=3.2.3->pyfolio) (0.2.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio) (2022.12.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio) (1.26.14)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [17]:
PATH_TO_MODEL_DIR = 'FinRLManystock/'
print(PATH_TO_MODEL_DIR)

import os
if not os.path.exists(PATH_TO_MODEL_DIR + 'save'):
    os.makedirs(PATH_TO_MODEL_DIR + 'save')
if not os.path.exists(PATH_TO_MODEL_DIR + 'trained'):
    os.makedirs(PATH_TO_MODEL_DIR + 'trained')
if not os.path.exists(PATH_TO_MODEL_DIR + 'tensorboard'):
    os.makedirs(PATH_TO_MODEL_DIR + 'tensorboard')
if not os.path.exists(PATH_TO_MODEL_DIR + 'results'):
    os.makedirs(PATH_TO_MODEL_DIR + 'results')

FinRLManystock/

In [18]:
dow_30_ticker = ['AAPL','MSFT','JPM','V','RTX','PG','GS','NKE','DIS','AXP',
                 'HD','INTC','WMT','IBM','MRK','UNH','KO','CAT','TRV','JNJ', 
                  'CVX','MCD','VZ','CSCO','XOM','BA','MMM','PFE','WBA','DD']
data_df = YahooDownloader(start_date = '2015-01-01',
                          end_date = '2021-01-01',
                          ticker_list = dow_30_ticker).fetch_data()
data_df.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (45330, 8)

,date,open,high,low,close,volume,tic,day
0,2015-01-02,24.347176,27.332500,27.860001,27.847500,212818400,AAPL,4
1,2015-01-02,80.322266,93.019997,93.940002,93.169998,2437500,AXP,4
2,2015-01-02,113.657219,129.949997,131.839996,131.070007,4294200,BA,4
3,2015-01-02,70.367180,91.879997,92.370003,91.769997,3767900,CAT,4
4,2015-01-02,20.326622,27.610001,28.120001,27.860001,22926500,CSCO,4

In [22]:
tech_indicator_list=[]
## you can add more technical indicators
## visit https://github.com/jealous/stockstats for different names
tech_indicator_list=tech_indicator_list+['kdjk','open_2_sma','boll','close','wr_10','dma','trix']
print(tech_indicator_list)

fe = FeatureEngineer(
                    use_technical_indicator=True,
                    tech_indicator_list = tech_indicator_list,
                    use_turbulence=False,
                    user_defined_feature = False)

data_df = fe.preprocess_data(data_df)
data_df.head()

['kdjk', 'open_2_sma', 'boll', 'close', 'wr_10', 'dma', 'trix']
Successfully added technical indicators

,date,open,high,low,close_x,volume,tic,day,kdjk,open_2_sma,boll,close_y,wr_10,dma,trix
0,2015-01-02,24.347176,27.332500,27.860001,27.847500,212818400,AAPL,4,34.123271,24.347176,27.847500,27.847500,-97.630188,0.0,0.0
1511,2015-01-02,80.322266,93.019997,93.940002,93.169998,2437500,AXP,4,61.231863,80.322266,93.169998,93.169998,-16.304411,0.0,0.0
3022,2015-01-02,113.657219,129.949997,131.839996,131.070007,4294200,BA,4,46.913391,113.657219,131.070007,131.070007,-59.259827,0.0,0.0
4533,2015-01-02,70.367180,91.879997,92.370003,91.769997,3767900,CAT,4,74.149617,70.367180,91.769997,91.769997,22.448852,0.0,0.0
6044,2015-01-02,20.326622,27.610001,28.120001,27.860001,22926500,CSCO,4,50.326805,20.326622,27.860001,27.860001,-49.019586,0.0,0.0

In [24]:
df = data_df
# add covariance matrix as states
df=df.sort_values(['date','tic'],ignore_index=True)
df.index = df.date.factorize()[0]

cov_list = []
# look back is one year
lookback=252
for i in range(lookback,len(df.index.unique())):
  data_lookback = df.loc[i-lookback:i,:]
  price_lookback=data_lookback.pivot_table(index = 'date',columns = 'tic', values = 'close_x')
  return_lookback = price_lookback.pct_change().dropna()
  covs = return_lookback.cov().values 
  cov_list.append(covs)
  
df_cov = pd.DataFrame({'date':df.date.unique()[lookback:],'cov_list':cov_list})
df = df.merge(df_cov, on='date')
df = df.sort_values(['date','tic']).reset_index(drop=True)
df.head()

,date,open,high,low,close_x,volume,tic,day,kdjk,open_2_sma,boll,close_y,wr_10,dma,trix,cov_list
0,2016-01-04,23.860584,26.337500,26.342501,25.652500,270597600,AAPL,0,-15.874316,23.850388,27.756000,25.652500,-181.899292,-1.977800,-0.386834,"[[0.000473231474786466, 0.00011891961334344143..."
1,2016-01-04,59.173836,67.589996,68.180000,68.089996,9248300,AXP,0,43.558311,60.031803,69.676000,68.089996,-103.797631,-2.206600,-0.134199,"[[0.000473231474786466, 0.00011891961334344143..."
2,2016-01-04,126.005104,140.500000,141.699997,141.380005,5719500,BA,0,37.742874,127.839115,144.929002,141.380005,-105.663567,-2.384598,-0.069453,"[[0.000473231474786466, 0.00011891961334344143..."
3,2016-01-04,54.018639,67.989998,68.080002,66.879997,8586900,CAT,0,53.688883,54.006725,67.264500,66.879997,-73.955832,-1.983201,-0.107942,"[[0.000473231474786466, 0.00011891961334344143..."
4,2016-01-04,20.057253,26.410000,26.420000,26.389999,35827100,CSCO,0,47.778483,20.262307,26.991500,26.389999,-102.222272,-0.501400,-0.026222,"[[0.000473231474786466, 0.00011891961334344143..."

In [ ]:
train = data_split(df, start = '2015-01-01', end = '2019-01-01')
trade = data_split(df, start = '2019-01-01', end = '2021-01-01')
train.to_csv(PATH_TO_MODEL_DIR + 'save' + '/train_MULTI.csv',index=False)
trade.to_csv(PATH_TO_MODEL_DIR + 'save' + '/trade_MULTI.csv',index=False)

In [ ]:
stock_dimension = len(train.tic.unique())
state_space = 1 + 2*stock_dimension + len(tech_indicator_list)*stock_dimension
#state_space = 156
print(f"Stock data Dimensions: {stock_dimension}, State Spaces: {state_space}")
env_kwargs = {
    "hmax": 100, 
    "initial_amount": 1000000, 
    #"transaction_cost_pct": 0.001, 
    "buy_cost_pct":0.001,
    "sell_cost_pct":0.001,
    "state_space": state_space, 
    "stock_dim": stock_dimension, 
    "tech_indicator_list": config.TECHNICAL_INDICATORS_LIST, 
    "action_space": stock_dimension, 
    "reward_scaling": 1e-4}
e_train_gym = StockTradingEnv(df = train, **env_kwargs)
env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))

In [ ]:
agent = DRLAgent(env = env_train)
A2C_PARAMS = {"n_steps": 5, "ent_coef": 0.005, "learning_rate": 0.0002}
model_a2c = agent.get_model(model_name="a2c",model_kwargs = A2C_PARAMS)
trained_a2c = agent.train_model(model=model_a2c, 
                                tb_log_name='a2c',
                                total_timesteps=100000)

In [ ]:
trained_a2c.save(PATH_TO_MODEL_DIR + config.TRAINED_MODEL_DIR+'/trained_a2c.model')

In [ ]:
trade.head()

In [ ]:
e_trade_gym = StockTradingEnv(df = trade, **env_kwargs)
df_account_value, df_actions = DRLAgent.DRL_prediction(model=trained_a2c, environment = e_trade_gym)

In [ ]:
print(df_account_value)
df_actions.head()

In [ ]:
from finrl.trade.backtest import backtest_stats, backtest_plot
print("==============Results===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value)
perf_stats_all = pd.DataFrame(perf_stats_all)

In [ ]:
%matplotlib inline
backtest_plot(account_value=df_account_value, baseline_ticker = 'AAPL',
             baseline_start = '2019-01-01', baseline_end = '2021-01-01')